name: "vprofile IAC Debug"

on:
  push:
    branches:
      - main
      - stage
  pull_request:
    branches:
      - main

jobs:
  debug-aws-credentials:
    name: "Debug AWS Credentials"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Print AWS Access Key ID
        run: echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_ID }}"

      - name: Print AWS Secret Access Key
        run: echo "AWS_SECRET_ACCESS_KEY is set"

      - name: Print Bucket TF State
        run: echo "BUCKET_TF_STATE=${{ secrets.BUCKET_TF_STATE }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Verify AWS credentials
        run: aws sts get-caller-identity
